spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:postgresql://localhost:5432/findNearBy
        username: postgres
        password: syspass
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 5MB
server:
    port: 8081